public void onSensorChanged(SensorEvent event)
protected void registerListener()
protected void unregisterListener()
public boolean jumped()
public void onAccuracyChanged(Sensor sensor, int accuracy)
