public float getLeftBound()
public float getRightBound()
public float getTopBound()
public float getBottomBound()
public void doDraw(Canvas canvas)
public void update(long elapsedTime)
public void scroll(float vel, long elapsedTime )
public void deactivate()
public float getHeight()
public float getWidth()
public void hide()
public void show()
public boolean hidden()
public boolean isPersistent()
public void setWidth(float width)
public void setHeight( float height )
public Rect getRect()
