public void update(long elapsedTime)
public void spewFire()
public void scroll(float amt, long elapsedTime)
public void doDraw(Canvas c)
public float getLeftBound()
public float getRightBound()
public float getTopBound()
public float getBottomBound()
public void deactivate()
public void hide()
public void show()
public boolean hidden()
public boolean isPersistent()
public float getWidth()
public float getHeight()
public void setWidth(float width)
public void setHeight(float height)
public void moveBy( float x, float y )
public void transition()
public boolean doChecks()
public void doActions( long elapsedTime )
public void transition()
public boolean doChecks()
public void doActions(long elapsedTime)
