public void update(long elapsedTime)
public void fire()
public void doDraw(Canvas canvas)
public void die( long currentTime )
public void AICheckMoveBounds()
private boolean AIHasPlatformToLand()
public void jump()
public boolean isVulnerable()
public void guard()
public void unGuard()
public void updateAI()
private void updateAIBattle()
private void updateAISleep()
private void updateAIFollow()
private void goToBattleMode()
private void goToFollowMode()
private void checkGuard()
