public void flipSprite()
public void doDraw(Canvas canvas)
public int getState()
public void fall()
public void rest()
public void jump()
public void run(long st)
public void fire(long time)
public void saveBoundaries(int leftBound, int rightBound)
public boolean checkFallFromBlock()
private boolean horizCol( Projectile p )
private boolean vertCol( Projectile p )
public void updateBlock( Block mBlock )
public void land( Block mBlock)
public void setState( int newstate )
public int getCurrentImg()
public void incrementImage()
public boolean getDirection()
public void setGravity(int grav)
public void setRunLength(int l)
