public void update( long elapsedTime )
public void land( Block b )
public void jump()
private void moveFeet(float feetPosition)
public boolean checkFallFromBlock()
private void fall()
public Block getOnBlock()
public void setOnBlock(Block onBlock)
public float getDy()
public void setDy(float mDy)
public float getDx()
public void setDx(float mDx)
public boolean isInAir()
public void setInAir(boolean inAir)
public boolean isRunning()
public void setRunning(boolean running)
