public void update( long elapsedTime)
public void doDraw( Canvas canvas )
public boolean updateAnimation( long elapsedTime )
public void startAnimation( int animationNumber )
public void stopOnFrame(int animationNum, int frameNum)
public void startAnimation(int animationNumber, int speed)
public void startAnimation(int number, int speed, int startFrame, boolean repeat)
public void flash(int color, long duration)
public void setTint(int color)
public boolean animationIsPlaying()
public void clearTint()
public void clearFlash()
public float getLeftBound()
public float getRightBound()
public float getTopBound()
public float getBottomBound()
public void scroll(float amt, long elapsedTime)
public void deactivate()
public void hide()
public void show()
public boolean hidden()
public boolean isPersistent()
public void setLeftBound(float mLeftBound)
public void setTopBound(float mTopBound)
public void setRightBound(float mRightBound)
public void setBottomBound(float mBottomBound)
public float getWidth()
public void setWidth(float mWidth)
public float getHeight()
public void setHeight(float mHeight)
public void setPersistent(boolean val)
public void rotate(float degrees)
public float getRotation()
public void setRotation(float rotation)
public SpriteResources getSpriteResources()
public void flip()
public boolean isFlipped()
public Paint getPaint()
public int getHealth()
public void setHealth(int health)
public void decrementHealth()
