public void update(long elapsedTime)
public void fire()
public void land(Block b)
public void die()
public void startRunning( float velocity )
public void stopRunning()
public void setAnims( int runAnim )
public void doSlash()
public boolean doChecks()
public void doActions(long elapsedTime)
public void transition()
public boolean doChecks()
public void doActions(long elapsedTime)
public void transition()
public boolean doChecks()
public void doActions(long elapsedTime)
public void transition()
public void transition()
public boolean doChecks()
public void doActions(long elapsedTime)
