public void printText( String str, Canvas canvas, Paint paint, int x, int y )
public void surfaceCreated(SurfaceHolder holder)
public void surfaceChanged(SurfaceHolder holder, int format, int width, int height)
public void surfaceDestroyed(SurfaceHolder holder)
public void doDraw(Canvas canvas)
public void addBlock(int left, int right, int top, int bottom, int color)
public boolean onTouchEvent(MotionEvent event)
public boolean touchHandleFlying(MotionEvent event)
public boolean touchHandlePlatformerMode(MotionEvent event)
public void moveHero(float speed)
public static void checkBlocks(long mElapsed)
public static void checkEnemyProjectiles(long mElapsed)
public void showMenu()
public boolean isGameOver()
public boolean isMenu()
public static int getCurrentLevel()
public static void setCurrentLevel(int currentLevel)
private void setupUI()
public void gameStartLevelOne(Context context)
public void complete()
public void gameStartLevelTwo(Context context)
private void gameStartLevelThree(Context context)
private void gameStartLevelFour(Context context)
private void initializeHero()
public void leaveMenu()
public void restartGame(Context context)
public void loadBitmapsLevelOne()
public static void removeFromLists( GameObject mObj )
public void generateMountains()
public void loadBitmapsLevelOneTwo()
public ViewThread getThread()
public static int getGameState()
public void setGameState(int gameState)
