public SpriteAnimation[] getSpriteAnimations()
public Bitmap getCurrentFrame()
public Bitmap getInitialFrame()
public void startAnimation(int animationNum, int startFrame)
public void stopOnFrame(int animationNum, int frameNum)
public boolean updateAnimation()
public void createFlippedBitmaps()
public Bitmap getLastFrame()
public Bitmap getSpeechBubble()
public Resources getAndroidResources()
public SpriteAnimation getCurrentAnimation()
