public void doDraw(Canvas canvas)
public void update(long elapsedTime)
public void hide()
public void show()
public boolean hidden()
public void deactivate()
public void moveFeet(float feetpos)
public float getLeftBound()
public float getRightBound()
public float getTopBound()
public float getBottomBound()
public float getYMiddle()
public void changeXDir()
public void changeYDir()
public float getScaleFactor()
public void scroll(float vel, long elapsedTime)
public boolean isPersistent()
public void setPersistent(boolean val)
public float getHeight()
public float getWidth()
public float getVelocity()
public void setWidth(float width)
public void setHeight(float height)
