public void start(int startFrame)
public boolean update()
public Bitmap getCurrentFrame()
public void setCurrentFrame(int frameNum)
public int getLength()
public Bitmap getInitialFrame( )
public void setBmps(Bitmap[] newBmps)
public void makeFlippedBmps()
public Bitmap[] flipBmpHorizontal( Bitmap[] input )
public Bitmap getBitmap( int bmpNum )
public Bitmap getFinalFrame()
public void setAnimSpeed(int speed)
public boolean isRepeat()
public void setRepeat(boolean repeat)
public void stop()
public boolean isPlaying()
